# Generated by Django 6.0.3 on 2026-03-24 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymemberprofile',
            old_name='style_preference',
            new_name='style_preferences',
        ),
    ]
